# -*- coding: utf-8 -*-
"""ShakespeareTextGen_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xFIiN-CDqKgALB1wL3W4qPAmR1N5KeEj

Project Overview :
In this notebook, we performed fine-tuning of a pre-trained BERT Generation Encoder-Decoder model,
which combines a BertGenerationEncoder and a BertGenerationDecoder, to generate new text in Shakespearean style.
We used a ready-made model and libraries (transformers), so there was no need to train a model from scratch — we only adapted it to our data.
For fine-tuning, we downloaded The Complete Works of Shakespeare (pg100.txt) from Project Gutenberg:
https://www.gutenberg.org/cache/epub/100/pg100.txt

We created input-output pairs of 50-word sequences as input and the same sequence shifted by one word as output.

We trained and saved models under several configurations for comparison:

30,000 pairs for 1 epoch (30K EPOCH 1)

30,000 pairs for 2 epochs (30K EPOCH 2)

100,000 pairs for 1 epoch (100K EPOCH 1)

100,000 pairs for 2 epochs (100K EPOCH 2)

100,000 pairs for 3 epochs (100K EPOCH 3)

 These trained models were first saved in our Google Drive for future use and performance comparison.
Later, we also uploaded them to Hugging Face and made them public so they are accessible for sharing, evaluation, and reuse.
You can view and access all of these models and the evaluation dataset at:
https://huggingface.co/NahlaAboromi

Finally, we built an interactive interface that uses these models directly from Hugging Face for generating Shakespearean-style text based on user input.
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers==4.28.1

# 🚀 התקנת ספריות
!pip install transformers datasets

# 📚 ייבוא ספריות
import requests
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import (
    BertTokenizer,
    BertGenerationEncoder,
    BertGenerationDecoder,
    EncoderDecoderModel,
)
from torch.optim import AdamW
import os

# ⚡ בדיקת חומרה
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('✅ Using device:', device)

# 📥 הורדת טקסט של שייקספיר
print('Downloading Shakespeare text...')
url = 'https://www.gutenberg.org/cache/epub/100/pg100.txt'
shakespeare_text = requests.get(url).text

# ✂ יצירת זוגות קלט-פלט
def create_pairs(text, block_size=50, max_pairs=100000):
    words = text.split()
    pairs = []
    for i in range(len(words) - block_size - 1):
        input_text = ' '.join(words[i:i + block_size])
        output_text = ' '.join(words[i + 1:i + block_size + 1])
        pairs.append({'input': input_text, 'output': output_text})
        if len(pairs) >= max_pairs:
            break
    return pairs

# 📚 טעינת טוקניזר ומודלים
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
tokenizer.bos_token_id = 101
tokenizer.eos_token_id = 102
tokenizer.pad_token_id = 0

encoder = BertGenerationEncoder.from_pretrained('bert-base-uncased', bos_token_id=101, eos_token_id=102)
decoder = BertGenerationDecoder.from_pretrained(
    'bert-base-uncased',
    add_cross_attention=True,
    is_decoder=True,
    bos_token_id=101,
    eos_token_id=102
)

model = EncoderDecoderModel(encoder=encoder, decoder=decoder)
model.config.decoder_start_token_id = tokenizer.bos_token_id
model.decoder.config.decoder_start_token_id = tokenizer.bos_token_id
model.config.pad_token_id = tokenizer.pad_token_id
model.config.eos_token_id = tokenizer.eos_token_id
model.to(device)

# 📦 בניית Dataset
class ShakespeareDataset(Dataset):
    def __init__(self, pairs, tokenizer, max_length=128):
        self.pairs = pairs
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        item = self.pairs[idx]
        input_enc = self.tokenizer(item['input'], padding='max_length', truncation=True,
                                   max_length=self.max_length, return_tensors='pt')
        output_enc = self.tokenizer(item['output'], padding='max_length', truncation=True,
                                    max_length=self.max_length, return_tensors='pt')
        return {
            'input_ids': input_enc.input_ids.squeeze(),
            'attention_mask': input_enc.attention_mask.squeeze(),
            'labels': output_enc.input_ids.squeeze()
        }

# 📊 אימון עבור 30K עם 1 אפוקים
pairs = create_pairs(shakespeare_text, max_pairs=30000)
dataset = ShakespeareDataset(pairs, tokenizer)
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

optimizer = AdamW(model.parameters(), lr=5e-5)
model.train()
print('🔥 Starting training...')
import time
start_time = time.time()

for epoch in range(1):
    total_loss = 0
    for i, batch in enumerate(dataloader):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )
        loss = outputs.loss
        total_loss += loss.item()
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if (i + 1) % 100 == 0:
            print(f'Epoch {epoch+1} Batch {i+1} Loss: {loss.item():.4f}')
    print(f'✅ Epoch {epoch+1} Total Loss: {total_loss:.4f}')

# 💾 שמירת המודל
output_dir = "/content/drive/MyDrive/shakespeare_bert_base_30KEPOCH1"
os.makedirs(output_dir, exist_ok=True)
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)
print(f"📁 Model saved to: {output_dir}")

!zip -r shakespeare_bert_base_30KEPOCH1.zip /content/drive/MyDrive/shakespeare_bert_base_30KEPOCH1
from google.colab import files
files.download("shakespeare_bert_base_30KEPOCH1.zip")
end_time = time.time()
print(f"⏱ Total training time: {(end_time - start_time)/60:.2f} minutes")

# 📊 אימון עבור 30K עם 2 אפוקים
pairs = create_pairs(shakespeare_text, max_pairs=30000)
dataset = ShakespeareDataset(pairs, tokenizer)
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

optimizer = AdamW(model.parameters(), lr=5e-5)
model.train()
print('🔥 Starting training...')
import time
start_time = time.time()

for epoch in range(2):
    total_loss = 0
    for i, batch in enumerate(dataloader):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )
        loss = outputs.loss
        total_loss += loss.item()
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if (i + 1) % 100 == 0:
            print(f'Epoch {epoch+1} Batch {i+1} Loss: {loss.item():.4f}')
    print(f'✅ Epoch {epoch+1} Total Loss: {total_loss:.4f}')


# 💾 שמירת המודל
output_dir = "/content/drive/MyDrive/shakespeare_bert_base_30KEPOCH2"
os.makedirs(output_dir, exist_ok=True)
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)
print(f"📁 Model saved to: {output_dir}")

!zip -r shakespeare_bert_base_30KEPOCH2.zip /content/drive/MyDrive/shakespeare_bert_base_30KEPOCH2
from google.colab import files
files.download("shakespeare_bert_base_30KEPOCH2.zip")
end_time = time.time()
print(f"⏱ Total training time: {(end_time - start_time)/60:.2f} minutes")

# 📊 אימון עבור 100K עם 1 אפוקים
pairs = create_pairs(shakespeare_text, max_pairs=100000)
dataset = ShakespeareDataset(pairs, tokenizer)
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

optimizer = AdamW(model.parameters(), lr=5e-5)
model.train()
print('🔥 Starting training...')
import time
start_time = time.time()

for epoch in range(1):
    total_loss = 0
    for i, batch in enumerate(dataloader):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )
        loss = outputs.loss
        total_loss += loss.item()
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if (i + 1) % 100 == 0:
            print(f'Epoch {epoch+1} Batch {i+1} Loss: {loss.item():.4f}')
    print(f'✅ Epoch {epoch+1} Total Loss: {total_loss:.4f}')

# 💾 שמירת המודל
output_dir = "/content/drive/MyDrive/shakespeare_bert_base_100KEPOCH1"
os.makedirs(output_dir, exist_ok=True)
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)
print(f"📁 Model saved to: {output_dir}")

!zip -r shakespeare_bert_base_100KEPOCH1.zip /content/drive/MyDrive/shakespeare_bert_base_100KEPOCH1
from google.colab import files
files.download("shakespeare_bert_base_100KEPOCH1.zip")
end_time = time.time()
print(f"⏱ Total training time: {(end_time - start_time)/60:.2f} minutes")

# 🚀 This script continues training a BERT EncoderDecoder model on Shakespeare text for one more epoch (Epoch 2),
# loading the previously saved model from Epoch 1 and printing ETA every 100 batches.

import os
import time
from datetime import timedelta
from transformers import BertTokenizer, EncoderDecoderModel
from torch.optim import AdamW

from torch.utils.data import DataLoader
import torch  # אל תשכחי לייבא

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 📥 Load the model saved after Epoch 1
load_path = "/content/drive/MyDrive/shakespeare_bert_base_100KEPOCH1"
model = EncoderDecoderModel.from_pretrained(load_path).to(device)
tokenizer = BertTokenizer.from_pretrained(load_path)

# 🔁 Recreate the dataset (same text and pairs)
pairs = create_pairs(shakespeare_text, max_pairs=100000)
dataset = ShakespeareDataset(pairs, tokenizer)
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

# 🧠 Define optimizer
optimizer = AdamW(model.parameters(), lr=5e-5)
model.train()

# ⚙️ Continue training for 1 more epoch (Epoch 2)
total_epochs = 1
output_name = "100K_EPOCH2"
total_batches = len(dataloader)

print(f"🔥 Continuing training for {total_epochs} more epoch(s)...")
start_time = time.time()

for epoch in range(total_epochs):
    epoch_start = time.time()
    total_loss = 0

    for i, batch in enumerate(dataloader):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )
        loss = outputs.loss
        total_loss += loss.item()
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        # ETA calculation
        batches_done = epoch * total_batches + (i + 1)
        total_done = total_epochs * total_batches
        elapsed = time.time() - start_time
        avg_time = elapsed / batches_done
        remaining = avg_time * (total_done - batches_done)
        eta = str(timedelta(seconds=int(remaining)))

        if (i + 1) % 100 == 0 or i == total_batches - 1:
            print(f"Epoch {epoch+1} Batch {i+1}/{total_batches} Loss: {loss.item():.4f} | ETA: {eta}")

    print(f'✅ Epoch {epoch+1} complete. Total Loss: {total_loss:.4f} | Duration: {timedelta(seconds=int(time.time() - epoch_start))}')

# 💾 Save the updated model to a new directory for Epoch 2
output_dir = f"/content/drive/MyDrive/shakespeare_bert_base_{output_name}"
os.makedirs(output_dir, exist_ok=True)
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)

print(f"📁 Model saved to: {output_dir}")

# 🚀 This script continues training a BERT EncoderDecoder model on Shakespeare text for one more epoch (Epoch 3),
# loading the previously saved model from Epoch 2 and printing ETA every 100 batches.

import os
import time
from datetime import timedelta
from transformers import BertTokenizer, EncoderDecoderModel, AdamW
from torch.utils.data import DataLoader

# 📥 טען את המודל השמור מה-EPOCH2
load_path = "/content/drive/MyDrive/shakespeare_bert_base_100K_EPOCH2"
model = EncoderDecoderModel.from_pretrained(load_path).to(device)
tokenizer = BertTokenizer.from_pretrained(load_path)

# 🔁 צור את הנתונים שוב (אותו טקסט, אותם זוגות)
pairs = create_pairs(shakespeare_text, max_pairs=100000)
dataset = ShakespeareDataset(pairs, tokenizer)
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

# 🧠 הגדר אופטימייזר
optimizer = AdamW(model.parameters(), lr=5e-5)
model.train()

# ⚙️ המשך אימון לעוד 1 אפוק (כלומר Epoch 3)
total_epochs = 1
output_name = "100K_EPOCH3"
total_batches = len(dataloader)

print(f"🔥 Continuing training for {total_epochs} more epoch(s)...")
start_time = time.time()

for epoch in range(total_epochs):
    epoch_start = time.time()
    total_loss = 0

    for i, batch in enumerate(dataloader):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )
        loss = outputs.loss
        total_loss += loss.item()
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        # ETA חישוב
        batches_done = epoch * total_batches + (i + 1)
        total_done = total_epochs * total_batches
        elapsed = time.time() - start_time
        avg_time = elapsed / batches_done
        remaining = avg_time * (total_done - batches_done)
        eta = str(timedelta(seconds=int(remaining)))

        if (i + 1) % 100 == 0 or i == total_batches - 1:
            print(f"Epoch {epoch+1} Batch {i+1}/{total_batches} Loss: {loss.item():.4f} | ETA: {eta}")

    print(f'✅ Epoch {epoch+1} complete. Total Loss: {total_loss:.4f} | Duration: {timedelta(seconds=int(time.time() - epoch_start))}')

# 💾 שמירה לתיקייה נפרדת עבור EPOCH3
output_dir = f"/content/drive/MyDrive/shakespeare_bert_base_{output_name}"
os.makedirs(output_dir, exist_ok=True)
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)

print(f"📁 Model saved to: {output_dir}")

""" Interactive Interface for Shakespeare Text Generation
This interface allows users to generate Shakespearean-style text using fine-tuned BERT models.
The models are loaded directly from Hugging Face (NahlaAboromi profile), where they were uploaded after training.
Users can select between different training configurations (30k / 100k pairs, different epochs), provide a prompt,
and generate text based on the selected model.


"""

from transformers import EncoderDecoderModel, BertTokenizer
import torch
import ipywidgets as widgets
from IPython.display import display

model_paths = {
    ("30k", "EPOCH1"): "NahlaAboromi/shakespeare-bert-30k-epoch1",
    ("30k", "EPOCH2"): "NahlaAboromi/shakespeare-bert-30k-epoch2",
    ("30k", "EPOCH3"): "NahlaAboromi/shakespeare-bert-30k-epoch3",
    ("100K", "EPOCH1"): "NahlaAboromi/shakespeare-bert-100k-epoch1",
    ("100K", "EPOCH2"): "NahlaAboromi/shakespeare-bert-100k-epoch2",
    ("100K", "EPOCH3"): "NahlaAboromi/shakespeare-bert-100k-epoch3",
}


# ווידג'טים
k_selector = widgets.Dropdown(options=["30k", "100K"], description="Dataset:")
epoch_selector = widgets.Dropdown(options=["EPOCH1", "EPOCH2", "EPOCH3"], description="Epoch:")
input_text = widgets.Textarea(
    value="When I consider everything that grows",
    description="Prompt:",
    layout=widgets.Layout(width="100%", height="100px")
)
generate_button = widgets.Button(description="Generate Shakespearean Text", button_style="success")
output_area = widgets.Output()

# פעולה
def generate_text(b):
    output_area.clear_output()
    with output_area:
        selected_key = (k_selector.value, epoch_selector.value)
        if selected_key not in model_paths:
            print("⚠️ No model found for this selection.")
            return

        folder = model_paths[selected_key]

        try:
            model = EncoderDecoderModel.from_pretrained(folder)
            tokenizer = BertTokenizer.from_pretrained(folder)
            model.eval()

            inputs = tokenizer(input_text.value, return_tensors="pt")
            output = model.generate(
                input_ids=inputs.input_ids,
                max_length=50,
                num_beams=5,
                no_repeat_ngram_size=2,
                early_stopping=True
            )

            generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
            print("📝 Generated Shakespearean Text:\n")
            print(generated_text)

        except Exception as e:
            print("❌ Error:", e)

generate_button.on_click(generate_text)

# הצגה
display(k_selector, epoch_selector, input_text, generate_button, output_area)